unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"
set -g mouse on 
set -g prefix C-s
set -g base-index 1

#act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set-option -g status-position top
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Salva automaticamente ogni 15 minuti e ripristina all'avvio
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

#minimal-tmux-status

set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#698DDA"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str "  tmux  "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "top"

set -g default-terminal "screen-256color"

set -g @minimal-tmux-right true
set -g @minimal-tmux-left true
set -g @minimal-tmux-expanded-icon " 󰊓 "

# To display images with image.nvim
set -gq allow-passthrough on
set -g visual-activity off
set-option -g focus-events on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
